# Generated by Django 5.0.2 on 2024-05-13 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_drinksmenu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrinksMenu',
            new_name='JuicesMenu',
        ),
    ]
